openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: '1.0'
servers:
  - url: 'http://localhost:8089'
    description: Inferred Url
tags:
  - name: Company
    description: Company Resource
paths:
  '/api/v1.0/market/company/delete/{companycode}':
    delete:
      tags:
        - Company
      summary: Deletes a company
      operationId: deleteCompanyUsingDELETE
      parameters:
        - name: companycode
          in: path
          description: companycode
          required: true
          style: simple
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Company not found
  /api/v1.0/market/company/getall:
    get:
      tags:
        - Company
      summary: Get information of all companies
      operationId: getAllCompaniesUsingGET
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/v1.0/market/company/info/{companycode}':
    get:
      tags:
        - Company
      summary: Get company information by company code
      operationId: getCompanyByCompanyCodeUsingGET
      parameters:
        - name: companycode
          in: path
          description: Company Code
          required: true
          style: simple
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Company not found
  /api/v1.0/market/company/register:
    post:
      tags:
        - Company
      summary: Add a company
      operationId: registerCompanyUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        '201':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Company Not Registered
components:
  schemas:
    Company:
      title: Company
      type: object
      properties:
        companyCEO:
          type: string
          description: name of CEO of the company
          example: Mr. ABC
        companyCode:
          type: integer
          description: company code of the company
          format: int64
          example: 11111
        companyName:
          type: string
          description: name of the company
          example: XYZ Corp
        companyTurnOver:
          minimum: 100000001
          exclusiveMinimum: false
          type: number
          description: turn over of the company
          format: bigdecimal
          example: 100000001
        companyWebsite:
          type: string
          description: website of the company
          example: www.xyz.com
        latestStockPrice:
          type: number
          description: latest stock price of the company
          format: double
          example: 400
        stockExchange:
          type: string
          description: stock exchange of the company
          example: NSE
