version: '3.9'

# Services
services:
  eureka-service:
    build:
      context: ./EurekaMicroService
      dockerfile: Dockerfile
    image: eureka-service:v1
    container_name: eureka-service
    ports:
    - 8761:8761
    networks:
      - backend

  company-service:
    build:
      context: ./CompanyMicroService
      dockerfile: Dockerfile
    image: company-service:v1
    container_name: company-service
    ports:
    - 8089:8089
    restart: always
    depends_on:
      - eureka-service
      - company-mysql-db
    environment:
      EUREKA_SERVER: http://eureka-service:8761/eureka
      SPRING_COMPANY_DATASOURCE_URL: jdbc:mysql://company-mysql-db:3308/companyDb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_COMPANY_DATASOURCE_USERNAME: appUser
      SPRING_COMPANY_DATASOURCE_PASSWORD: appPass
    networks:
      - backend

  stock-price-service:
    build:
      context: ./StockPriceMicroService
      dockerfile: Dockerfile
    image: stock-price-service:v1
    container_name: stock-price-service
    ports:
    - 8090:8090
    restart: always
    depends_on:
      - eureka-service
      - stock-mysql-db
    environment:
      EUREKA_SERVER: http://eureka-service:8761/eureka
      SPRING_STOCK_DATASOURCE_URL: jdbc:mysql://stock-mysql-db:3309/stockDb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_STOCK_DATASOURCE_USERNAME: appUser
      SPRING_STOCK_DATASOURCE_PASSWORD: appPass
    networks:
      - backend

  company-mysql-db:
    image: mysql:latest
    container_name: company-mysql-db
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: companyDb
      MYSQL_USER: appUser
      MYSQL_PASSWORD: appPass
      MYSQL_ROOT_PASSWORD: rootPass
    volumes:
      - company-db-data:/var/lib/mysql
    networks:
      - backend

  stock-mysql-db:
    image: mysql:latest
    container_name: stock-mysql-db
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: stockDb
      MYSQL_USER: appUser
      MYSQL_PASSWORD: appPass
      MYSQL_ROOT_PASSWORD: rootPass
    volumes:
      - stock-db-data:/var/lib/mysql
    networks:
      - backend

  # management

  grafana-service:
    build:
      context: ./MicroServiceManagement/grafana
      dockerfile: Dockerfile
    image: grafana-service
    container_name: grafana-service
    mem_limit: 256M
    ports:
    - 3000:3000
    networks:
      - backend

  prometheus-service:
    build:
      context: ./MicroServiceManagement/prometheus
      dockerfile: Dockerfile
    image: prometheus-service
    container_name: prometheus-service
    mem_limit: 256M
    ports:
    - 9091:9090
    networks:
      - backend

# Volumes
volumes:
  company-db-data:
  stock-db-data:

# Network
networks:
  backend: