global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: company-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['company-service:8089']

  - job_name: stock-price-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['stock-price-service:8090']